# Generated by Django 2.1.2 on 2018-10-04 04:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20181004_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('eslogan', models.CharField(max_length=255)),
                ('fec_campania', models.DateField()),
                ('horario', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Campañas',
            },
        ),
        migrations.CreateModel(
            name='Campania_insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('cod_campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Campania')),
            ],
            options={
                'verbose_name': 'Campaña insumos',
            },
        ),
        migrations.CreateModel(
            name='Fondo_Economico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_ahorro', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Fondo Economico',
                'verbose_name_plural': 'Fondos Economicos',
            },
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Insumos',
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Login',
            },
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('esterilizado', models.CharField(max_length=1)),
                ('chip', models.CharField(max_length=1)),
                ('fec_nac', models.DateField()),
            ],
            options={
                'verbose_name': 'Mascotas',
            },
        ),
        migrations.CreateModel(
            name='Origen_mascota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Origen mascota',
            },
        ),
        migrations.CreateModel(
            name='Raza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Razas',
            },
        ),
        migrations.CreateModel(
            name='Refugio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Refugios',
            },
        ),
        migrations.CreateModel(
            name='Tipo_campania',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipos de campaña',
            },
        ),
        migrations.CreateModel(
            name='Tipo_insumo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcionInsumo', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Tipos de Insumo',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_trabajador', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('ap_pat', models.CharField(max_length=100)),
                ('ap_mat', models.CharField(max_length=100)),
                ('fec_nac', models.DateField()),
                ('telefono', models.IntegerField()),
                ('direccion', models.CharField(max_length=255)),
                ('mail', models.CharField(max_length=50)),
                ('sueldo', models.IntegerField()),
                ('id_comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Comuna')),
                ('id_genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Genero')),
            ],
            options={
                'verbose_name': 'Trabajador',
                'verbose_name_plural': 'Trabajadores',
            },
        ),
        migrations.CreateModel(
            name='Transferencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_compania', models.IntegerField()),
                ('id_fondo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Fondo_Economico')),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Usuario')),
            ],
            options={
                'verbose_name': 'Transferencias',
            },
        ),
        migrations.CreateModel(
            name='Visita_adopcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adopcion', models.CharField(max_length=1)),
                ('cod_compania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Campania')),
                ('cod_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Mascota')),
                ('rut_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Usuario')),
            ],
            options={
                'verbose_name': 'Visitas de adopcion',
            },
        ),
        migrations.CreateModel(
            name='Visita_Medica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_visita', models.DateField()),
                ('hora', models.DateTimeField()),
                ('minuto', models.DateTimeField()),
                ('cod_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Mascota')),
                ('rut_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Trabajador')),
            ],
            options={
                'verbose_name': 'Visitas Medicas',
            },
        ),
        migrations.AddField(
            model_name='mascota',
            name='cod_refugio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Refugio'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='id_orig_masc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Origen_mascota'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='id_raza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Raza'),
        ),
        migrations.AddField(
            model_name='mascota',
            name='rut_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
        migrations.AddField(
            model_name='login',
            name='rut_trabajador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Trabajador'),
        ),
        migrations.AddField(
            model_name='login',
            name='rut_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Usuario'),
        ),
        migrations.AddField(
            model_name='insumo',
            name='id_tip_insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tipo_insumo'),
        ),
        migrations.AddField(
            model_name='campania_insumo',
            name='id_insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Insumo'),
        ),
        migrations.AddField(
            model_name='campania',
            name='id_tip_campania',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Tipo_campania'),
        ),
    ]
