# Generated by Django 2.1.2 on 2018-10-04 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20181004_0107'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='telefono',
            new_name='telefon',
        ),
    ]
